### ISSUE TITLE
Possible sdbm bug handling large amounts of keys/data

### ISSUE THREAD

**Issue by jamesbriggs** [davidar/sdbm#1]
When inserting more than 50,000 records, I recently saw this error. Nothing's changed in 12 years except sdbm package on Redhat 7, so maybe add a test for large keys/data.

sdbm store returned -1, errno 9, key "20120731001937.EE68D2AFE0@x3.develooper.com" at /usr/local/apache/htdocs/openwebmail/openwebmail/shares/maildb.pl line 529.

sub _update_index_with_msghash {
   my ($r_FDB, $id, $r_message)=@_;
   $$r_FDB{$id}=msgattr2string(${$r_message}{offset}, ${$r_message}{from}, ${$r_message}{to},
      ${$r_message}{date}, ${$r_message}{subject}, ${$r_message}{'content-type'}, ${$r_message}{status},
      ${$r_message}{size}, ${$r_message}{references}, ${$r_message}{charset},
      ${$r_message}{headersize}, ${$r_message}{headerchksum});
   return 0;
}

**Comment by davidar** [comment]
Sorry, this is just a mirror of the sdbm source code. You might have better luck contacting the original author. If you wanted to contribute a test case to this repository, please submit a pull request.
